# Generated by Django 2.2.2 on 2020-01-14 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(default='Product name', max_length=100, verbose_name='Product name')),
                ('description', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(help_text='Unique URL', unique=True)),
                ('price', models.FloatField()),
            ],
        ),
    ]
